### ISSUE TITLE
update keeps prefs?

### ISSUE THREAD

**Issue by yippiekahee** [willsALMANJ/Zutilo#114] opened 2019-12-04 11:08 UTC
Zutilo 2.0.4 misbehaves on latest Zotero. I'd like to update Zutilo, automatic update does not seem to function. Do I keep my preferences if I install the zutilo.XPI over the existing version?

ps. documentation states that Firefox cannot save XPI. This is not the case: rightclick & save

**Comment by willsALMANJ** [comment] 2019-12-04 18:01
Hmm, that is strange about automatic updates not working. Installing over the existing xpi will maintain your preferences.

The documentation should say that that could happen, but it does happen in some cases. Based on your report, it seems that it does not always happen, but I don't know in which cases it is a problem. I do know how to fix it so that right-click & save always works, but I haven't had time to make that change yet. I will probably fix it with the next release.

**Comment by yippiekahee** [comment] 2019-12-04 20:16
Thank you for your response and creating Zutilo. Update settings were 'default', whatever that may be. Changed it to 'on', 9 hours ago. But still not updated. Documentation: I referred to README.md. And after rightclick I use 'save link as'
attached the prefs screen of Zutilo 2.0.4.. ![zutilo prefs 2019-12-04-11-51-47](https://user-images.githubusercontent.com/32000999/70176921-9e6ed780-16d9-11ea-9bfd-5b404aef3fef.png)

I updated manually. Prefs weird view is fixed after update. But still my shift-T shortcut 'item pane: add tag' is not what it was. It shifts to the Tag-tab, but does not add&open a tag-field so I can start typing.

**Comment by willsALMANJ** [comment] 2019-12-04 22:14
You can click on the gear icon and choose "Check for updates" to force it to check right away. When I make the next release, I will test that it updates automatically for me at least.

The weird prefs view was due to a recent change to Zotero and that was fixed in Zutilo version 3.2.1.

I understand about the right-click/save issue -- but for some people it doesn't work.

The issue you mention about the add tag shortcut is #113.

**Comment by willsALMANJ** [comment] 2019-12-06 16:52
I just pushed a new release to fix #113. Afterwards, I tested updating with Zotero 5.0.77 and Zotero 5.0.80. I did notice that Zutilo failed to update the first time I tried, but then it worked after that. I couldn't reproduce the failure. If this becomes a big enough problem, we make it its own issue and look into it further. I am curious to know if "Check for updates" downloads 3.3.1 for you.

I will close this issue for now.

**Closed by willsALMANJ** 2019-12-06 16:52 UTC

**Comment by yippiekahee** [comment] 2019-12-06 20:28
![image](https://user-images.githubusercontent.com/32000999/70353719-51703a00-186e-11ea-9f03-4bbee754893a.png)
This is a bit weird: I updated a few days ago, but it states that it's been more than a year ago..
But anyhow: automatic update did not update (yet?), but Check for updates went fine and my Shift+T shortcut to immediately enter a tag works like a charm. Thank you
